import os
import asyncio
from flask import Flask
from threading import Thread
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, CallbackQueryHandler, filters, ContextTypes, ConversationHandler
import edge_tts

# --- CONFIGURATION ---
TOKEN = os.getenv("BOT_TOKEN")
# မင်းရဲ့ Channel ID ကို @ နဲ့ သေချာထည့်ပါ (ဥပမာ "@mychannel")
CHANNEL_ID = "@reeac_99" 

# Flask Server for Render
app = Flask('')
@app.route('/')
def home(): return "Bot is Online"
def run(): app.run(host='0.0.0.0', port=10000)

# Conversation States
JOIN_CHECK, GET_TEXT, SELECT_VOICE = range(3)

# Voices Mapping (Thiha, Nilar - MM / Zaw Zaw, Su Su - EN/Multi)
VOICES = {
    "Thiha (Male)": "my-MM-ThihaNeural",
    "Nilar (Female)": "my-MM-NilarNeural",
    "Zaw Zaw (Male)": "en-US-GuyNeural",
    "Su Su (Female)": "en-US-EmmaNeural"
}

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    try:
        # Check Channel Membership
        member = await context.bot.get_chat_member(chat_id=CHANNEL_ID, user_id=user_id)
        if member.status in ['left', 'kicked']:
            keyboard = [[InlineKeyboardButton("Join Channel", url=f"https://t.me/{CHANNEL_ID.replace('@','')}")],
                        [InlineKeyboardButton("I have joined ✅", callback_data="check_join")]]
            await update.message.reply_text("ရှေ့ဆက်ဖို့ ကျွန်ုပ်တို့၏ Channel ကို အရင် Join ပေးပါ။", reply_markup=InlineKeyboardMarkup(keyboard))
            return JOIN_CHECK
        
        await update.message.reply_text("မင်္ဂလာပါ! အသံပြောင်းလိုသော စာသားကို ရိုက်ထည့်ပေးပါ။")
        return GET_TEXT
    except Exception:
        await update.message.reply_text(f"Error: {CHANNEL_ID} မှာ Bot ကို Admin ခန့်ထားဖို့ လိုအပ်ပါတယ်။")
        return ConversationHandler.END

async def check_join_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    user_id = query.from_user.id
    await query.answer()
    
    member = await context.bot.get_chat_member(chat_id=CHANNEL_ID, user_id=user_id)
    if member.status not in ['left', 'kicked']:
        # Join ပြီးတာနဲ့ စာကို ဖျက်ပေးမယ်
        await query.message.delete()
        await context.bot.send_message(chat_id=user_id, text="ကျေးဇူးတင်ပါတယ်။ အခု အသံပြောင်းလိုတဲ့ စာသားကို ရိုက်ထည့်နိုင်ပါပြီ။")
        return GET_TEXT
    else:
        await query.message.reply_text("Join မလုပ်ရသေးပါ။ ကျေးဇူးပြု၍ အရင် Join ပါ။")
        return JOIN_CHECK

async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data['text_to_convert'] = update.message.text
    keyboard = [[InlineKeyboardButton(name, callback_data=name)] for name in VOICES.keys()]
    await update.message.reply_text("အသုံးပြုလိုသော အသံကို ရွေးချယ်ပေးပါ -", reply_markup=InlineKeyboardMarkup(keyboard))
    return SELECT_VOICE

async def handle_voice_selection(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    voice_name = query.data
    text = context.user_data.get('text_to_convert')
    await query.answer()
    
    msg = await query.edit_message_text("အသံဖိုင် ပြောင်းလဲနေပါသည်... ခဏစောင့်ပါ။")
    
    try:
        output_file = f"voice_{query.from_user.id}.mp3"
        communicate = edge_tts.Communicate(text, VOICES[voice_name])
        await communicate.save(output_file)
        
        await query.message.reply_audio(audio=open(output_file, 'rb'), caption=f"Generated by {voice_name}")
        await msg.delete()
        os.remove(output_file)
    except Exception as e:
        await query.edit_message_text(f"Error: {str(e)}")
    
    return GET_TEXT # နောက်ထပ်စာသား ထပ်ရိုက်နိုင်အောင် ပြန်ထားပေးမယ်

def main():
    Thread(target=run).start()
    application = Application.builder().token(TOKEN).build()

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler("start", start)],
        states={
            JOIN_CHECK: [CallbackQueryHandler(check_join_callback, pattern="^check_join$")],
            GET_TEXT: [MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text)],
            SELECT_VOICE: [CallbackQueryHandler(handle_voice_selection)]
        },
        fallbacks=[CommandHandler("start", start)]
    )

    application.add_handler(conv_handler)
    application.run_polling(drop_pending_updates=True) # Conflict မဖြစ်အောင် စာဟောင်းတွေကို ဖျက်ခိုင်းမယ်

if __name__ == '__main__':
    main()
