import logging
import os
import asyncio
import tempfile
import json
import re
from functools import wraps

import edge_tts
from flask import Flask
import threading
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    ContextTypes,
    filters,
    ConversationHandler,
)
from telegram.constants import ParseMode

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# Flask app for Render keep-alive
app = Flask(__name__)

@app.route("/")
def home():
    return "Myanmar TTS Bot is running!"

# Bot Configuration
TOKEN = os.getenv("BOT_TOKEN") # Read token from environment variable
CHANNEL_USERNAME = "@reeac_99" # Replace with your actual channel username
CHANNEL_LINK = "https://t.me/reeac_99"

# User data persistence file
USER_DATA_FILE = "user_data.json"

def load_user_data():
    if os.path.exists(USER_DATA_FILE):
        with open(USER_DATA_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_user_data(data):
    with open(USER_DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)

user_settings = load_user_data()

# Conversation States
(SELECT_LANGUAGE, CHECK_MEMBERSHIP, GET_TEXT, SELECT_VOICE) = range(4)

# Language specific messages
MESSAGES = {
    'en': {
        'select_lang_prompt': "Please select your preferred language:",
        'join_channel_prompt': "You must join our official channel to use this bot.",
        'join_channel_button': "📢 Join Official Channel",
        'joined_button': "✅ I have joined",
        'not_joined_alert': "You haven't joined yet. Please join the channel and try again.",
        'welcome_message': "Welcome! Please send the text you want to convert to speech.",
        'not_member_rejoin': "You are no longer a member of the channel. Please rejoin to continue using the bot: {}",
        'send_some_text': "Please send some text.",
        'select_voice_prompt': "Please select a voice for your text:",
        'generating_audio': "⏳ Generating audio... Please wait.",
        'audio_caption': "Generated by Myanmar TTS Bot",
        'done_send_more': "Done! You can send more text anytime.",
        'error_generating': "❌ An error occurred while generating the audio. Please try again later.",
        'bot_session_ended': "Bot session ended. Send /start to restart.",
        'change_language_button': "Change Language 🌐",
        'language_changed': "Language changed to English.",
        'language_changed_my': "ဘာသာစကားကို မြန်မာလို ပြောင်းလဲပြီးပါပြီ။",
        'unknown_command': "Unknown command. Please use the buttons provided or send text for TTS.",
    },
    'my': {
        'select_lang_prompt': "သင်နှစ်သက်သော ဘာသာစကားကို ရွေးချယ်ပါ။",
        'join_channel_prompt': "Bot ၏ ဝန်ဆောင်မှုများကို အသုံးပြုရန် ကျွန်ုပ်တို့၏ Official Channel ကို joinထားရပါမည်။",
        'join_channel_button': "📢 Official Channel ကို Joinရန်",
        'joined_button': "✅ ဝင်ရောက်ပြီးပါပြီ",
        'not_joined_alert': "Channel ကို မဝင်ရသေးပါ။ ကျေးဇူးပြု၍ Channel သို့ဝင်ရောက်ပြီး ထပ်မံကြိုးစားပါ။",
        'welcome_message': "ကြိုဆိုပါတယ်။ သင်အသံပြောင်းလိုသော စာသားကို ပေးပို့နိုင်ပါပြီ။",
        'not_member_rejoin': "သင်သည် Channel မှ ထွက်ခွာသွားပါပြီ။ Bot ကိုဆက်လက်အသုံးပြုရန် Channel သို့ ပြန်လည်ဝင်ရောက်ပေးပါ။ {}",
        'send_some_text': "ကျေးဇူးပြု၍ စာသားတစ်ခုခု ပေးပို့ပါ။",
        'select_voice_prompt': "သင်၏စာသားအတွက် အသံပုံစံကို ရွေးချယ်ပါ။",
        'generating_audio': "⏳ အသံဖိုင်ဖန်တီးနေပါသည်။ ခဏစောင့်ပါ။",
        'audio_caption': "Myanmar TTS Bot မှ ဖန်တီးထားသည်",
        'done_send_more': "ပြီးပါပြီ! သင်စာသားများ ထပ်မံပေးပို့နိုင်ပါသည်။",
        'error_generating': "❌ အသံဖိုင်ဖန်တီးရာတွင် အမှားအယွင်းတစ်ခု ဖြစ်ပေါ်ခဲ့ပါသည်။ ကျေးဇူးပြု၍ နောက်မှ ထပ်မံကြိုးစားပါ။",
        'bot_session_ended': "Bot session ပြီးဆုံးပါပြီ။ ပြန်လည်စတင်ရန် /start ကို ပေးပို့ပါ။",
        'change_language_button': "ဘာသာစကားပြောင်းရန် 🌐",
        'language_changed': "Language changed to English.",
        'language_changed_my': "ဘာသာစကားကို မြန်မာလို ပြောင်းလဲပြီးပါပြီ။",
        'unknown_command': "မသိသော command။ ပေးထားသော ခလုတ်များကို အသုံးပြုပါ သို့မဟုတ် စာသားကို အသံပြောင်းရန် ပေးပို့ပါ။",
    }
}

def get_message(user_lang, key):
    return MESSAGES.get(user_lang, MESSAGES['en']).get(key, MESSAGES['en'][key])

# Voice Options (10 styles) with distinct names and personalities
VOICE_STYLES = {
    "my-MM-NilarNeural": {"name_en": "Nilar (Female - Sweet)", "name_my": "နီလာ (အမျိုးသမီး - ချိုသာ)", "voice_id": "my-MM-NilarNeural"},
    "en-US-JennyNeural": {"name_en": "Poe (Female - Professional)", "name_my": "ပိုး (အမျိုးသမီး - ကျွမ်းကျင်)", "voice_id": "en-US-JennyNeural"},
    "en-US-AriaNeural": {"name_en": "Shwe (Female - Calm)", "name_my": "ရွှေ (အမျိုးသမီး - တည်ငြိမ်)", "voice_id": "en-US-AriaNeural"},
    "en-GB-SoniaNeural": {"name_en": "Aye (Female - Energetic)", "name_my": "အေး (အမျိုးသမီး - တက်ကြွ)", "voice_id": "en-GB-SoniaNeural"},
    "en-AU-NatashaNeural": {"name_en": "May (Female - Soft)", "name_my": "မေ (အမျိုးသမီး - နူးညံ့)", "voice_id": "en-AU-NatashaNeural"},
    
    "my-MM-ThihaNeural": {"name_en": "Thura (Male - Deep)", "name_my": "သူရ (အမျိုးသား - အသံနက်)", "voice_id": "my-MM-ThihaNeural"},
    "en-US-GuyNeural": {"name_en": "Kyaw (Male - Bold)", "name_my": "ကျော် (အမျိုးသား - ပြတ်သား)", "voice_id": "en-US-GuyNeural"},
    "en-GB-RyanNeural": {"name_en": "Min (Male - Young)", "name_my": "မင်း (အမျိုးသား - လူငယ်)", "voice_id": "en-GB-RyanNeural"},
    "en-CA-LiamNeural": {"name_en": "Zaw (Male - Narrative)", "name_my": "ဇော် (အမျိုးသား - ဇာတ်ကြောင်းပြော)", "voice_id": "en-CA-LiamNeural"},
    "en-AU-WilliamNeural": {"name_en": "Htet (Male - Friendly)", "name_my": "ထက် (အမျိုးသား - ဖော်ရွေ)", "voice_id": "en-AU-WilliamNeural"},
}

def get_user_setting(user_id, key, default=None):
    return user_settings.get(str(user_id), {}).get(key, default)

def set_user_setting(user_id, key, value):
    user_id_str = str(user_id)
    if user_id_str not in user_settings:
        user_settings[user_id_str] = {}
    user_settings[user_id_str][key] = value
    save_user_data(user_settings)

async def check_channel_membership(user_id: int, context: ContextTypes.DEFAULT_TYPE) -> bool:
    """Checks if the user is a member of the specified channel."""
    try:
        chat_member = await context.bot.get_chat_member(CHANNEL_USERNAME, user_id)
        return chat_member.status in ["member", "administrator", "creator"]
    except Exception as e:
        logger.error(f"Error checking channel membership for user {user_id}: {e}")
        return False

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Starts the bot flow: Language Selection."""
    user = update.effective_user
    keyboard = [
        [InlineKeyboardButton("မြန်မာစာ 🇲🇲", callback_data="set_lang_my")],
        [InlineKeyboardButton("English 🇺🇸", callback_data="set_lang_en")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(
        get_message("en", 'select_lang_prompt'), # Default to English for initial prompt
        reply_markup=reply_markup
    )
    return SELECT_LANGUAGE

async def select_language_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    user = query.from_user
    lang_code = query.data.replace("set_lang_", "")
    await query.answer()

    set_user_setting(user.id, 'language', lang_code)
    user_lang = lang_code

    # Now check channel membership
    if not await check_channel_membership(user.id, context):
        keyboard = [
            [InlineKeyboardButton(get_message(user_lang, 'join_channel_button'), url=CHANNEL_LINK)],
            [InlineKeyboardButton(get_message(user_lang, 'joined_button'), callback_data="joined")]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)

        await query.edit_message_text(
            get_message(user_lang, 'join_channel_prompt'),
            reply_markup=reply_markup, parse_mode=ParseMode.HTML
        )
        return CHECK_MEMBERSHIP
    else:
        await query.edit_message_text(get_message(user_lang, 'welcome_message'))
        await send_persistent_keyboard(update, context, user_lang)
        return GET_TEXT

async def joined_check_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Handles the 'I have joined' button click and verifies membership."""
    query = update.callback_query
    user = query.from_user
    user_lang = get_user_setting(user.id, 'language', 'en')
    await query.answer()

    if await check_channel_membership(user.id, context):
        await query.edit_message_text(get_message(user_lang, 'welcome_message'))
        await send_persistent_keyboard(update, context, user_lang)
        return GET_TEXT
    else:
        await query.answer(get_message(user_lang, 'not_joined_alert'), show_alert=True)
        return CHECK_MEMBERSHIP

async def send_persistent_keyboard(update: Update, context: ContextTypes.DEFAULT_TYPE, user_lang: str):
    reply_markup = ReplyKeyboardMarkup(
        [[KeyboardButton(get_message(user_lang, 'change_language_button'))]],
        resize_keyboard=True
    )
    if update.callback_query:
        await update.callback_query.message.reply_text(
            "", # No text for this message, just the keyboard
            reply_markup=reply_markup
        )
    else:
        await update.message.reply_text(
            "", # No text for this message, just the keyboard
            reply_markup=reply_markup
        )

async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Presents voice options after receiving text."""
    user = update.effective_user
    user_lang = get_user_setting(user.id, 'language', 'en')

    if not await check_channel_membership(user.id, context):
        await update.message.reply_text(
            get_message(user_lang, 'not_member_rejoin').format(CHANNEL_LINK),
            reply_markup=ReplyKeyboardRemove()
        )
        return ConversationHandler.END # End conversation if not a member

    text = update.message.text
    if not text:
        await update.message.reply_text(get_message(user_lang, 'send_some_text'))
        return GET_TEXT

    context.user_data['current_text_for_tts'] = text

    keyboard = []
    # Group voices by gender for better display
    female_voices = []
    male_voices = []
    for voice_id, details in VOICE_STYLES.items():
        if "Female" in details['name_en'] or "အမျိုးသမီး" in details['name_my']:
            female_voices.append(InlineKeyboardButton(details[f'name_{user_lang}'].split('(')[0].strip(), callback_data=f"select_voice_{voice_id}"))
        else:
            male_voices.append(InlineKeyboardButton(details[f'name_{user_lang}'].split('(')[0].strip(), callback_data=f"select_voice_{voice_id}"))
    
    # Arrange in rows of 2
    for i in range(0, len(female_voices), 2):
        keyboard.append(female_voices[i:i+2])
    for i in range(0, len(male_voices), 2):
        keyboard.append(male_voices[i:i+2])

    reply_markup = InlineKeyboardMarkup(keyboard)

    await update.message.reply_text(
        get_message(user_lang, 'select_voice_prompt'),
        reply_markup=reply_markup
    )
    return SELECT_VOICE

async def select_voice_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Generates TTS audio with the selected voice."""
    query = update.callback_query
    user = query.from_user
    user_lang = get_user_setting(user.id, 'language', 'en')
    voice_id = query.data.replace("select_voice_", "")
    await query.answer()

    text_to_convert = context.user_data.get('current_text_for_tts')
    if not text_to_convert:
        await query.edit_message_text(get_message(user_lang, 'error_generating')) # Use generic error for no text
        return GET_TEXT

    await query.edit_message_text(get_message(user_lang, 'generating_audio'))

    try:
        communicate = edge_tts.Communicate(text_to_convert, voice_id)
        
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tmp_file:
            output_path = tmp_file.name
        
        await communicate.save(output_path)

        with open(output_path, "rb") as audio_file:
            await context.bot.send_document(
                chat_id=update.effective_chat.id,
                document=audio_file,
                filename="myanmar_tts.mp3",
                caption=get_message(user_lang, 'audio_caption')
            )
        
        os.remove(output_path)
        
        await context.bot.send_message(
            chat_id=update.effective_chat.id,
            text=get_message(user_lang, 'done_send_more'),
            reply_markup=ReplyKeyboardMarkup([[KeyboardButton(get_message(user_lang, 'change_language_button'))]], resize_keyboard=True)
        )

    except Exception as e:
        logger.error(f"Error generating TTS for user {user.id}: {e}") # Log the exact error
        await context.bot.send_message(
            chat_id=update.effective_chat.id,
            text=get_message(user_lang, 'error_generating'),
            reply_markup=ReplyKeyboardMarkup([[KeyboardButton(get_message(user_lang, 'change_language_button'))]], resize_keyboard=True)
        )

    return GET_TEXT

async def change_language_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    user = update.effective_user
    keyboard = [
        [InlineKeyboardButton("မြန်မာစာ 🇲🇲", callback_data="set_lang_my")],
        [InlineKeyboardButton("English 🇺🇸", callback_data="set_lang_en")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(
        get_message(get_user_setting(user.id, 'language', 'en'), 'select_lang_prompt'),
        reply_markup=reply_markup
    )
    return SELECT_LANGUAGE # Re-enter language selection state

async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Cancels and ends the conversation."""
    user_lang = get_user_setting(update.effective_user.id, 'language', 'en')
    await update.message.reply_text(get_message(user_lang, 'bot_session_ended'), reply_markup=ReplyKeyboardRemove())
    return ConversationHandler.END

async def unknown_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user_lang = get_user_setting(update.effective_user.id, 'language', 'en')
    await update.message.reply_text(get_message(user_lang, 'unknown_command'))

def run_flask_app():
    """Runs the Flask app in a separate thread."""
    port = int(os.environ.get("PORT", 10000)) # Default to 10000 if PORT env var is not set
    logger.info(f"Flask app starting on port {port} in background...")
    app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False)

def main() -> None:
    """Start the bot."""
    # Start the Flask app in a separate thread
    flask_thread = threading.Thread(target=run_flask_app)
    flask_thread.daemon = True # Set as daemon thread so it exits when main program exits
    flask_thread.start()

    application = Application.builder().token(TOKEN).build()

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler("start", start)],
        states={
            SELECT_LANGUAGE: [CallbackQueryHandler(select_language_callback, pattern="^set_lang_")],
            CHECK_MEMBERSHIP: [CallbackQueryHandler(joined_check_callback, pattern="^joined$")],
            GET_TEXT: [
                MessageHandler(filters.TEXT & ~filters.COMMAND & filters.Regex(r"^(Change Language 🌐|ဘာသာစကားပြောင်းရန် 🌐)$"), change_language_command),
                MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text),
            ],
            SELECT_VOICE: [CallbackQueryHandler(select_voice_callback, pattern="^select_voice_")],
        },
        fallbacks=[CommandHandler("cancel", cancel), MessageHandler(filters.COMMAND, unknown_command)],
        allow_reentry=True
    )

    application.add_handler(conv_handler)
    application.add_handler(MessageHandler(filters.COMMAND, unknown_command))
    application.add_handler(MessageHandler(filters.TEXT & filters.Regex(r"^(Change Language 🌐|ဘာသာစကားပြောင်းရန် 🌐)$"), change_language_command))

    logger.info(">>> BOT IS NOW POLLING AND READY! <<<")
    application.run_polling()

if __name__ == "__main__":
    main()
